apiVersion: v1
kind: Secret
metadata:
  name: zta-secrets
  namespace: zta
type: Opaque
stringData:
  SA_PASSWORD: "ChangeMe_123!"
  ConnectionStrings__PolicyDb: "Server=zta-mssql,1433;Database=ZtaPolicy;User Id=sa;Password=ChangeMe_123!;TrustServerCertificate=true"
